import { TopicList } from './types';

export default () => ({
	projectList: <TopicList[]>[
		{
			bgSrc: '/imgs/box-images/box-image-4.png',
			bgAlt: 'pages.our-projects.projects.project-1.bgAlt',
			logoSrc: '/imgs/box-images/small-innotech-image.png',
			logoAlt: 'pages.our-projects.projects.project-1.logoAlt',
			subtitle: 'pages.our-projects.projects.project-1.subtitle',
			text: 'pages.our-projects.projects.project-1.text',
			title: 'pages.our-projects.projects.project-1.title',
			location: '/contact',
		},
		{
			bgSrc: '/imgs/box-images/box-image-4.png',
			bgAlt: 'pages.our-projects.projects.project-2.bgAlt',
			logoSrc: '/imgs/box-images/small-innotech-image.png',
			logoAlt: 'pages.our-projects.projects.project-2.logoAlt',
			subtitle: 'pages.our-projects.projects.project-2.subtitle',
			text: 'pages.our-projects.projects.project-2.text',
			title: 'pages.our-projects.projects.project-2.title',
			location: '/contact',
		},
		{
			bgSrc: '/imgs/box-images/box-image-4.png',
			bgAlt: 'pages.our-projects.projects.project-3.bgAlt',
			logoSrc: '/imgs/box-images/small-innotech-image.png',
			logoAlt: 'pages.our-projects.projects.project-3.logoAlt',
			subtitle: 'pages.our-projects.projects.project-3.subtitle',
			text: 'pages.our-projects.projects.project-3.text',
			title: 'pages.our-projects.projects.project-3.title',
			location: '/contact',
		},
		{
			bgSrc: '/imgs/box-images/box-image-4.png',
			bgAlt: 'pages.our-projects.projects.project-4.bgAlt',
			logoSrc: '/imgs/box-images/small-lastmile-image.png',
			logoAlt: 'pages.our-projects.projects.project-4.logoAlt',
			subtitle: 'pages.our-projects.projects.project-4.subtitle',
			text: 'pages.our-projects.projects.project-4.text',
			title: 'pages.our-projects.projects.project-4.title',
			location: '/contact',
		},
		{
			bgSrc: '/imgs/box-images/box-image-4.png',
			bgAlt: 'pages.our-projects.projects.project-5.bgAlt',
			logoSrc: '/imgs/box-images/small-lastmile-image.png',
			logoAlt: 'pages.our-projects.projects.project-5.logoAlt',
			subtitle: 'pages.our-projects.projects.project-5.subtitle',
			text: 'pages.our-projects.projects.project-5.text',
			title: 'pages.our-projects.projects.project-5.title',
			location: '/contact',
		},
		{
			bgSrc: '/imgs/box-images/box-image-4.png',
			bgAlt: 'pages.our-projects.projects.project-6.bgAlt',
			logoSrc: '/imgs/box-images/small-lastmile-image.png',
			logoAlt: 'pages.our-projects.projects.project-6.logoAlt',
			subtitle: 'pages.our-projects.projects.project-6.subtitle',
			text: 'pages.our-projects.projects.project-6.text',
			title: 'pages.our-projects.projects.project-6.title',
			location: '/contact',
		},
	],
});
